package:
  name: fumi_tools
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: https://github.com/tfehlmann/fumi-tools.git
  git_rev: {{ GIT_DESCRIBE_TAG }}

build:
  number: 0
  ignore_run_exports:
    - zlib

requirements:
  build:
    - cmake
    - make
    - autoconf
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib
  run:
    - zlib
    - pigz

about:
  home: https://github.com/tfehlmann/fumi-tools
  license: MIT
  license_file: LICENSE
  summary: |
    Tool for deduplicating UMIs

